input_data = open("input.txt", "r").read()
"""The rest of the file was generated by chatGPT lol"""
print(sum((r1_s<=r2_s and r2_e<=r1_e) or (r2_s<=r1_s and r1_e<=r2_e) for ((r1_s,r1_e),(r2_s,r2_e)) in [(tuple(map(int,x.split("-"))),tuple(map(int,y.split("-")))) for z in input_data.split("\n") if z for x,y in (z.split(","),)]))

pairs = []
for line in input_data.split("\n"):
    if line:
        # Split the line on the comma to extract the two ranges in the pair.
        range_a, range_b = line.split(",")

        # Split each range on the hyphen to extract the start and end of the range.
        start_a, end_a = map(int, range_a.split("-"))
        start_b, end_b = map(int, range_b.split("-"))

        # Add the ranges to the list of pairs.
        pairs.append(((start_a, end_a), (start_b, end_b)))

# Count the number of pairs of assignments where one range fully contains the other.
count = 0
for range_a, range_b in pairs:
    start_a, end_a = range_a
    start_b, end_b = range_b

    # Check whether the start and end of range A are within the start and end of range B,
    # or whether the start and end of range B are within the start and end of range A.
    if (start_a <= start_b and end_b <= end_a) or (start_b <= start_a and end_a <= end_b):
        count += 1

print(count)